<?php
/**
 * U2I Process — CMS configuration & shared helpers (OVH shared hosting).
 *
 * ── MySQL (OVH) ─────────────────────────────────────────────────────────────
 * In the OVH Control Panel: Web Cloud → Databases → create a MySQL database.
 * It gives you: server (…mysql.db), database name, user, password.
 * Fill the four constants below with those values, then open /api/install.php
 * once in a browser to create the tables.
 *
 * ── Local development (XAMPP) ───────────────────────────────────────────────
 * Do NOT edit this file. Create public/api/config.local.php with your local
 * values (see README — "Run fully local with XAMPP"). That file is optional,
 * git-ignored, and blocked from HTTP access by .htaccess.
 */

declare(strict_types=1);

// ── Local overrides FIRST (config.local.php, XAMPP / dev machine) ───────────
// This file uses define() and may override ANY default below. It is optional,
// git-ignored, and blocked from HTTP access by .htaccess. See
// config.local.example.php for a template.
if (is_file(__DIR__ . '/config.local.php')) {
    require __DIR__ . '/config.local.php';
}

// ── Production defaults (OVH) — used ONLY for values not overridden locally ─
if (!defined('DB_HOST')) {
    define('DB_HOST', 'u2iprocesscom.mysql.db');
}
if (!defined('DB_NAME')) {
    define('DB_NAME', 'u2iprocesscomdb');
}
if (!defined('DB_USER')) {
    define('DB_USER', 'u2iprocesscomdb');
}
if (!defined('DB_PASS')) {
    define('DB_PASS', 'CHANGE_ME');
}

// Admin dashboard: create the account from the dashboard on first login
// (setup mode) — it stores a real password_hash() in the `admins` table.
// DEFAULT_ADMIN_* below is only a fallback used when the DB is unreachable;
// the hash must be generated with:
//   php -r "echo password_hash('yourpass', PASSWORD_DEFAULT);"
// Leave DEFAULT_ADMIN_HASH empty ('') to disable the fallback.
if (!defined('DEFAULT_ADMIN_USER')) {
    define('DEFAULT_ADMIN_USER', 'admin');
}
if (!defined('DEFAULT_ADMIN_HASH')) {
    define('DEFAULT_ADMIN_HASH', '');
}
if (!defined('PLUNK_API_KEY')) {
    define('PLUNK_API_KEY', '');
}

// ── Resolved runtime values (local override → production default) ───────────
if (!defined('U2I_DB_HOST')) {
    define('U2I_DB_HOST', DB_HOST);
}
if (!defined('U2I_DB_NAME')) {
    define('U2I_DB_NAME', DB_NAME);
}
if (!defined('U2I_DB_USER')) {
    define('U2I_DB_USER', DB_USER);
}
if (!defined('U2I_DB_PASS')) {
    define('U2I_DB_PASS', DB_PASS);
}
if (!defined('U2I_ADMIN_USER')) {
    define('U2I_ADMIN_USER', DEFAULT_ADMIN_USER);
}
if (!defined('U2I_ADMIN_HASH')) {
    define('U2I_ADMIN_HASH', DEFAULT_ADMIN_HASH);
}
if (!defined('U2I_PLUNK_API_KEY')) {
    define('U2I_PLUNK_API_KEY', PLUNK_API_KEY);
}

// ── Uploads (FIX: these constants were referenced but never defined) ────────
if (!defined('UPLOAD_DIR')) {
    define('UPLOAD_DIR', __DIR__ . '/uploads');
}
/** MIME type → safe extension. SVG is served with a hardened CSP header. */
if (!defined('ALLOWED_IMAGE_TYPES')) {
    define('ALLOWED_IMAGE_TYPES', [
        'image/jpeg' => 'jpg',
        'image/png' => 'png',
        'image/webp' => 'webp',
        'image/gif' => 'gif',
        'image/svg+xml' => 'svg',
    ]);
}
if (!defined('UPLOAD_MAX_BYTES')) {
    define('UPLOAD_MAX_BYTES', 12 * 1024 * 1024); // 12 MB
}

// ── Internal helpers ────────────────────────────────────────────────────────

function db(): PDO
{
    static $pdo = null;
    if ($pdo instanceof PDO) {
        return $pdo;
    }

    $dsn = sprintf('mysql:host=%s;dbname=%s;charset=utf8mb4', U2I_DB_HOST, U2I_DB_NAME);
    $pdo = new PDO($dsn, U2I_DB_USER, U2I_DB_PASS, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        PDO::ATTR_EMULATE_PREPARES => false,
    ]);

    return $pdo;
}

function json_response(array $payload, int $status = 200): void
{
    while (ob_get_level() > 0) {
        ob_end_clean(); // drop any stray warnings/notices before the JSON body
    }
    http_response_code($status);
    header('Content-Type: application/json; charset=utf-8');
    header('X-Content-Type-Options: nosniff');
    echo json_encode($payload, JSON_UNESCAPED_UNICODE);
    exit;
}

function read_json_body(): array
{
    $raw = file_get_contents('php://input');
    if (!is_string($raw) || trim($raw) === '') {
        return $_POST;
    }
    try {
        $data = json_decode($raw, true, 512, JSON_THROW_ON_ERROR);
    } catch (JsonException) {
        json_response(['ok' => false, 'message' => 'Invalid JSON payload.'], 400);
    }

    return is_array($data) ? $data : [];
}

function field(array $data, string $key): string
{
    return isset($data[$key]) && is_scalar($data[$key]) ? trim((string) $data[$key]) : '';
}

/** Fetch a boolean flag from a decoded JSON body. */
function flag(array $data, string $key): bool
{
    return !empty($data[$key]);
}

/** Fetch a positive int from a decoded JSON body (0 when absent/invalid). */
function int_field(array $data, string $key): int
{
    return isset($data[$key]) && is_numeric($data[$key]) ? (int) $data[$key] : 0;
}

/** URL-safe slug (accents folded, lowercase, dashes). */
function slugify(string $text): string
{
    $text = mb_strtolower(trim($text));
    if (function_exists('iconv')) {
        $folded = @iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $text);
        if (is_string($folded) && $folded !== '') {
            $text = $folded;
        }
    }
    $text = preg_replace('~[^a-z0-9]+~', '-', $text) ?? '';
    $text = trim($text, '-');

    return $text !== '' ? $text : 'sans-titre';
}

/**
 * Guarantee a unique slug in $table. $table must come from the internal
 * allow-list — never from user input (identifier injection guard).
 */
function unique_slug(string $table, string $base, int $excludeId = 0): string
{
    static $allowed = ['pages', 'articles', 'categories', 'tags'];
    if (!in_array($table, $allowed, true)) {
        throw new InvalidArgumentException('Unknown table for slug generation.');
    }

    $slug = $base;
    $i = 2;
    while (true) {
        $stmt = db()->prepare("SELECT COUNT(*) AS c FROM {$table} WHERE slug = ? AND id != ?");
        $stmt->execute([$slug, $excludeId]);
        if ((int) $stmt->fetch()['c'] === 0) {
            return $slug;
        }
        $slug = $base . '-' . $i++;
    }
}

function admin_session_start(): void
{
    if (session_status() !== PHP_SESSION_ACTIVE) {
        // Hardened session cookie (works on plain HTTP OVH hosting too).
        @ini_set('session.use_strict_mode', '1');
        @ini_set('session.use_only_cookies', '1');
        @ini_set('session.cookie_httponly', '1');
        @ini_set('session.cookie_samesite', 'Lax');
        if (($_SERVER['HTTPS'] ?? '') !== '' && ($_SERVER['HTTPS'] ?? 'off') !== 'off') {
            @ini_set('session.cookie_secure', '1');
        }
        session_name('u2i_admin_session');
        session_start();
    }
}

function admin_login(string $username, string $password): bool
{
    admin_session_start();

    $hash = admin_password_hash_for($username);
    if ($hash === null) {
        usleep(400000); // slow brute force
        return false;
    }

    // Guard against accounts seeded with a non-PHP placeholder hash (old
    // schema versions): password_verify() would always fail silently.
    if (!preg_match('/^\$2[aby]\$|^\$argon2/', $hash)) {
        json_response([
            'ok' => false,
            'message' => "Compte administrateur invalide (ancien schéma). Dans phpMyAdmin, exécutez « DELETE FROM admins; » puis rechargez /admin pour recréer le compte.",
        ], 409);
    }

    if (!password_verify($password, $hash)) {
        usleep(400000); // slow brute force
        return false;
    }

    session_regenerate_id(true);
    $_SESSION['admin'] = true;
    $_SESSION['admin_at'] = time();
    $_SESSION['admin_username'] = $username;

    return true;
}

/**
 * Look up a user's bcrypt hash: database `admins` table first (editable from
 * the dashboard), then the config/env credentials as fallback.
 */
function admin_password_hash_for(string $username): ?string
{
    try {
        $stmt = db()->prepare('SELECT password_hash FROM admins WHERE username = ? LIMIT 1');
        $stmt->execute([$username]);
        $row = $stmt->fetch();
        if (is_array($row) && $row['password_hash'] !== '') {
            return (string) $row['password_hash'];
        }
    } catch (Throwable) {
        // DB not installed/reachable — fall back to config credentials.
    }

    if (hash_equals(U2I_ADMIN_USER, $username) && U2I_ADMIN_HASH !== '') {
        return U2I_ADMIN_HASH;
    }

    return null;
}

function admin_logout(): void
{
    admin_session_start();
    $_SESSION = [];
    if (ini_get('session.use_cookies')) {
        $p = session_get_cookie_params();
        setcookie(session_name(), '', time() - 42000, $p['path'], $p['domain'], $p['secure'], $p['httponly']);
    }
    session_destroy();
}

function require_admin(): void
{
    admin_session_start();
    $timeout = 12 * 3600; // 12h idle logout
    if (empty($_SESSION['admin']) || (time() - (int) ($_SESSION['admin_at'] ?? 0)) > $timeout) {
        json_response(['ok' => false, 'message' => 'Not authenticated.'], 401);
    }
    $_SESSION['admin_at'] = time();
}

function csrf_token(): string
{
    admin_session_start();
    if (empty($_SESSION['csrf'])) {
        $_SESSION['csrf'] = bin2hex(random_bytes(32));
    }

    return (string) $_SESSION['csrf'];
}

function verify_csrf(string $token): void
{
    admin_session_start();
    if (empty($_SESSION['csrf']) || !hash_equals((string) $_SESSION['csrf'], $token)) {
        json_response(['ok' => false, 'message' => 'Invalid CSRF token.'], 403);
    }
}

function is_db_installed(): bool
{
    try {
        $tables = db()->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);

        return count($tables) > 0;
    } catch (Throwable) {
        return false;
    }
}

/**
 * Lightweight file-backed rate limiter (used for login attempts).
 * @return bool true when the action is allowed this time.
 */
function rate_limit_ok(string $scope, int $max, int $windowSeconds): bool
{
    $ip = $_SERVER['REMOTE_ADDR'] ?? '';
    if ($ip === '') {
        return true;
    }
    $dir = __DIR__ . '/cache';
    if (!is_dir($dir) && !@mkdir($dir, 0755, true) && !is_dir($dir)) {
        return true; // cannot persist state; don't lock admins out
    }

    $file = $dir . '/rl-' . hash('sha256', $scope . '|' . $ip) . '.json';
    $now = time();
    $hits = [];
    if (is_file($file)) {
        $decoded = json_decode((string) @file_get_contents($file), true);
        if (is_array($decoded)) {
            $hits = $decoded;
        }
    }
    $hits = array_values(array_filter($hits, static fn ($t): bool => is_int($t) || is_numeric($t) ? (int) $t > $now - $windowSeconds : false));

    if (count($hits) >= $max) {
        return false;
    }

    $hits[] = $now;
    @file_put_contents($file, json_encode($hits));

    return true;
}

/**
 * Move an uploaded image into /api/uploads with a random, safe filename.
 * @return array{url:string,width:int|null,height:int|null}
 */
function store_uploaded_image(array $file): array
{
    if (($file['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_OK) {
        json_response(['ok' => false, 'message' => "Échec de l'envoi du fichier."], 400);
    }
    if ((int) ($file['size'] ?? 0) > UPLOAD_MAX_BYTES) {
        json_response(['ok' => false, 'message' => 'Fichier trop volumineux (max 12 Mo).'], 400);
    }

    $tmp = (string) ($file['tmp_name'] ?? '');
    if ($tmp === '' || !is_uploaded_file($tmp)) {
        json_response(['ok' => false, 'message' => 'Fichier invalide.'], 400);
    }
    $mime = function_exists('mime_content_type') ? (mime_content_type($tmp) ?: '') : '';
    if ($mime === '' && function_exists('getimagesize')) {
        $info = @getimagesize($tmp);
        $mime = is_array($info) ? (string) $info['mime'] : '';
    }
    if (!isset(ALLOWED_IMAGE_TYPES[$mime])) {
        json_response(['ok' => false, 'message' => 'Type de fichier non autorisé (images uniquement).'], 400);
    }

    if (!is_dir(UPLOAD_DIR) && !mkdir(UPLOAD_DIR, 0755, true) && !is_dir(UPLOAD_DIR)) {
        json_response(['ok' => false, 'message' => "Impossible de créer le dossier d'upload."], 500);
    }

    $ext = ALLOWED_IMAGE_TYPES[$mime];
    $name = bin2hex(random_bytes(12)) . '.' . $ext;
    if (!move_uploaded_file($tmp, UPLOAD_DIR . '/' . $name)) {
        json_response(['ok' => false, 'message' => "Échec de l'enregistrement du fichier."], 500);
    }
    @chmod(UPLOAD_DIR . '/' . $name, 0644);

    $width = null;
    $height = null;
    if ($mime !== 'image/svg+xml') {
        $info = @getimagesize(UPLOAD_DIR . '/' . $name);
        if (is_array($info)) {
            $width = (int) $info[0];
            $height = (int) $info[1];
        }
    }

    return ['url' => '/api/uploads/' . $name, 'width' => $width, 'height' => $height];
}

/** Serve one upload with hardened headers (SVG gets a strict CSP). */
function serve_upload(string $filename): void
{
    $filename = basename($filename); // path-traversal guard
    $path = UPLOAD_DIR . '/' . $filename;
    if (!is_file($path)) {
        http_response_code(404);
        exit('Not found');
    }

    $ext = strtolower(pathinfo($path, PATHINFO_EXTENSION));
    $mimes = [
        'jpg' => 'image/jpeg',
        'jpeg' => 'image/jpeg',
        'png' => 'image/png',
        'webp' => 'image/webp',
        'gif' => 'image/gif',
        'svg' => 'image/svg+xml',
        'pdf' => 'application/pdf',
    ];
    $mime = $mimes[$ext] ?? 'application/octet-stream';

    header('Content-Type: ' . $mime);
    header('Content-Length: ' . (string) filesize($path));
    header('X-Content-Type-Options: nosniff');
    header('Cache-Control: public, max-age=2592000');
    if ($ext === 'svg' || $ext === 'pdf') {
        // SVG/PDF can carry scripts: forbid script execution when served.
        header("Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; img-src data:");
        header('Content-Disposition: inline; filename="' . $filename . '"');
    }

    readfile($path);
    exit;
}
